- name: copy MetalLB manifests
  become: yes
  template:
    src: metallb.yaml
    dest: /etc/metallb.yaml

- name: copy MetalLB config
  become: yes
  template:
    src: metallb-config.yaml
    dest: /etc/metallb-config.yaml

- name: create namespace
  become: yes
  command: kubectl create namespace metallb-system --kubeconfig=/etc/kubernetes/admin.conf

- name: install MetalLB config
  become: yes
  command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml

- name: install MetalLB
  become: yes
  command: kubectl apply -f /etc/metallb.yaml --kubeconfig=/etc/kubernetes/admin.conf
